// Code generated by protoc-gen-go. DO NOT EDIT.
// source: values.proto

package octosql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nulls struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nulls) Reset()         { *m = Nulls{} }
func (m *Nulls) String() string { return proto.CompactTextString(m) }
func (*Nulls) ProtoMessage()    {}
func (*Nulls) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0}
}

func (m *Nulls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nulls.Unmarshal(m, b)
}
func (m *Nulls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nulls.Marshal(b, m, deterministic)
}
func (m *Nulls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nulls.Merge(m, src)
}
func (m *Nulls) XXX_Size() int {
	return xxx_messageInfo_Nulls.Size(m)
}
func (m *Nulls) XXX_DiscardUnknown() {
	xxx_messageInfo_Nulls.DiscardUnknown(m)
}

var xxx_messageInfo_Nulls proto.InternalMessageInfo

type Phantoms struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phantoms) Reset()         { *m = Phantoms{} }
func (m *Phantoms) String() string { return proto.CompactTextString(m) }
func (*Phantoms) ProtoMessage()    {}
func (*Phantoms) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{1}
}

func (m *Phantoms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phantoms.Unmarshal(m, b)
}
func (m *Phantoms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phantoms.Marshal(b, m, deterministic)
}
func (m *Phantoms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phantoms.Merge(m, src)
}
func (m *Phantoms) XXX_Size() int {
	return xxx_messageInfo_Phantoms.Size(m)
}
func (m *Phantoms) XXX_DiscardUnknown() {
	xxx_messageInfo_Phantoms.DiscardUnknown(m)
}

var xxx_messageInfo_Phantoms proto.InternalMessageInfo

type Ints struct {
	Ints                 []int64  `protobuf:"varint,1,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ints) Reset()         { *m = Ints{} }
func (m *Ints) String() string { return proto.CompactTextString(m) }
func (*Ints) ProtoMessage()    {}
func (*Ints) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{2}
}

func (m *Ints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ints.Unmarshal(m, b)
}
func (m *Ints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ints.Marshal(b, m, deterministic)
}
func (m *Ints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ints.Merge(m, src)
}
func (m *Ints) XXX_Size() int {
	return xxx_messageInfo_Ints.Size(m)
}
func (m *Ints) XXX_DiscardUnknown() {
	xxx_messageInfo_Ints.DiscardUnknown(m)
}

var xxx_messageInfo_Ints proto.InternalMessageInfo

func (m *Ints) GetInts() []int64 {
	if m != nil {
		return m.Ints
	}
	return nil
}

type Floats struct {
	Floats               []float64 `protobuf:"fixed64,1,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Floats) Reset()         { *m = Floats{} }
func (m *Floats) String() string { return proto.CompactTextString(m) }
func (*Floats) ProtoMessage()    {}
func (*Floats) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{3}
}

func (m *Floats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Floats.Unmarshal(m, b)
}
func (m *Floats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Floats.Marshal(b, m, deterministic)
}
func (m *Floats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Floats.Merge(m, src)
}
func (m *Floats) XXX_Size() int {
	return xxx_messageInfo_Floats.Size(m)
}
func (m *Floats) XXX_DiscardUnknown() {
	xxx_messageInfo_Floats.DiscardUnknown(m)
}

var xxx_messageInfo_Floats proto.InternalMessageInfo

func (m *Floats) GetFloats() []float64 {
	if m != nil {
		return m.Floats
	}
	return nil
}

type Bools struct {
	Bools                []bool   `protobuf:"varint,1,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bools) Reset()         { *m = Bools{} }
func (m *Bools) String() string { return proto.CompactTextString(m) }
func (*Bools) ProtoMessage()    {}
func (*Bools) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{4}
}

func (m *Bools) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bools.Unmarshal(m, b)
}
func (m *Bools) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bools.Marshal(b, m, deterministic)
}
func (m *Bools) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bools.Merge(m, src)
}
func (m *Bools) XXX_Size() int {
	return xxx_messageInfo_Bools.Size(m)
}
func (m *Bools) XXX_DiscardUnknown() {
	xxx_messageInfo_Bools.DiscardUnknown(m)
}

var xxx_messageInfo_Bools proto.InternalMessageInfo

func (m *Bools) GetBools() []bool {
	if m != nil {
		return m.Bools
	}
	return nil
}

type Strings struct {
	Strings              []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strings) Reset()         { *m = Strings{} }
func (m *Strings) String() string { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()    {}
func (*Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{5}
}

func (m *Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strings.Unmarshal(m, b)
}
func (m *Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strings.Marshal(b, m, deterministic)
}
func (m *Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strings.Merge(m, src)
}
func (m *Strings) XXX_Size() int {
	return xxx_messageInfo_Strings.Size(m)
}
func (m *Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Strings proto.InternalMessageInfo

func (m *Strings) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type Times struct {
	Times                []*timestamp.Timestamp `protobuf:"bytes,1,rep,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Times) Reset()         { *m = Times{} }
func (m *Times) String() string { return proto.CompactTextString(m) }
func (*Times) ProtoMessage()    {}
func (*Times) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{6}
}

func (m *Times) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Times.Unmarshal(m, b)
}
func (m *Times) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Times.Marshal(b, m, deterministic)
}
func (m *Times) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Times.Merge(m, src)
}
func (m *Times) XXX_Size() int {
	return xxx_messageInfo_Times.Size(m)
}
func (m *Times) XXX_DiscardUnknown() {
	xxx_messageInfo_Times.DiscardUnknown(m)
}

var xxx_messageInfo_Times proto.InternalMessageInfo

func (m *Times) GetTimes() []*timestamp.Timestamp {
	if m != nil {
		return m.Times
	}
	return nil
}

type Durations struct {
	Durations            []*duration.Duration `protobuf:"bytes,1,rep,name=durations,proto3" json:"durations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Durations) Reset()         { *m = Durations{} }
func (m *Durations) String() string { return proto.CompactTextString(m) }
func (*Durations) ProtoMessage()    {}
func (*Durations) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{7}
}

func (m *Durations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Durations.Unmarshal(m, b)
}
func (m *Durations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Durations.Marshal(b, m, deterministic)
}
func (m *Durations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Durations.Merge(m, src)
}
func (m *Durations) XXX_Size() int {
	return xxx_messageInfo_Durations.Size(m)
}
func (m *Durations) XXX_DiscardUnknown() {
	xxx_messageInfo_Durations.DiscardUnknown(m)
}

var xxx_messageInfo_Durations proto.InternalMessageInfo

func (m *Durations) GetDurations() []*duration.Duration {
	if m != nil {
		return m.Durations
	}
	return nil
}

type Tuple struct {
	Fields               []*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{8}
}

func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetFields() []*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Object struct {
	Fields               map[string]*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{9}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Null
	//	*Value_Phantom
	//	*Value_Int
	//	*Value_Float
	//	*Value_Bool
	//	*Value_String_
	//	*Value_Time
	//	*Value_Duration
	//	*Value_Tuple
	//	*Value_Object
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{10}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null *Nulls `protobuf:"bytes,1,opt,name=null,proto3,oneof"`
}

type Value_Phantom struct {
	Phantom *Phantoms `protobuf:"bytes,2,opt,name=phantom,proto3,oneof"`
}

type Value_Int struct {
	Int *Ints `protobuf:"bytes,3,opt,name=int,proto3,oneof"`
}

type Value_Float struct {
	Float *Floats `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type Value_Bool struct {
	Bool *Bools `protobuf:"bytes,5,opt,name=bool,proto3,oneof"`
}

type Value_String_ struct {
	String_ *Strings `protobuf:"bytes,6,opt,name=string,proto3,oneof"`
}

type Value_Time struct {
	Time *Times `protobuf:"bytes,7,opt,name=time,proto3,oneof"`
}

type Value_Duration struct {
	Duration *Durations `protobuf:"bytes,8,opt,name=duration,proto3,oneof"`
}

type Value_Tuple struct {
	Tuple *Tuple `protobuf:"bytes,9,opt,name=tuple,proto3,oneof"`
}

type Value_Object struct {
	Object *Object `protobuf:"bytes,10,opt,name=object,proto3,oneof"`
}

func (*Value_Null) isValue_Value() {}

func (*Value_Phantom) isValue_Value() {}

func (*Value_Int) isValue_Value() {}

func (*Value_Float) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_String_) isValue_Value() {}

func (*Value_Time) isValue_Value() {}

func (*Value_Duration) isValue_Value() {}

func (*Value_Tuple) isValue_Value() {}

func (*Value_Object) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetNull() *Nulls {
	if x, ok := m.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return nil
}

func (m *Value) GetPhantom() *Phantoms {
	if x, ok := m.GetValue().(*Value_Phantom); ok {
		return x.Phantom
	}
	return nil
}

func (m *Value) GetInt() *Ints {
	if x, ok := m.GetValue().(*Value_Int); ok {
		return x.Int
	}
	return nil
}

func (m *Value) GetFloat() *Floats {
	if x, ok := m.GetValue().(*Value_Float); ok {
		return x.Float
	}
	return nil
}

func (m *Value) GetBool() *Bools {
	if x, ok := m.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return nil
}

func (m *Value) GetString_() *Strings {
	if x, ok := m.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return nil
}

func (m *Value) GetTime() *Times {
	if x, ok := m.GetValue().(*Value_Time); ok {
		return x.Time
	}
	return nil
}

func (m *Value) GetDuration() *Durations {
	if x, ok := m.GetValue().(*Value_Duration); ok {
		return x.Duration
	}
	return nil
}

func (m *Value) GetTuple() *Tuple {
	if x, ok := m.GetValue().(*Value_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *Value) GetObject() *Object {
	if x, ok := m.GetValue().(*Value_Object); ok {
		return x.Object
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Null)(nil),
		(*Value_Phantom)(nil),
		(*Value_Int)(nil),
		(*Value_Float)(nil),
		(*Value_Bool)(nil),
		(*Value_String_)(nil),
		(*Value_Time)(nil),
		(*Value_Duration)(nil),
		(*Value_Tuple)(nil),
		(*Value_Object)(nil),
	}
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{11}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Phantom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phantom) Reset()         { *m = Phantom{} }
func (m *Phantom) String() string { return proto.CompactTextString(m) }
func (*Phantom) ProtoMessage()    {}
func (*Phantom) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{12}
}

func (m *Phantom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phantom.Unmarshal(m, b)
}
func (m *Phantom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phantom.Marshal(b, m, deterministic)
}
func (m *Phantom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phantom.Merge(m, src)
}
func (m *Phantom) XXX_Size() int {
	return xxx_messageInfo_Phantom.Size(m)
}
func (m *Phantom) XXX_DiscardUnknown() {
	xxx_messageInfo_Phantom.DiscardUnknown(m)
}

var xxx_messageInfo_Phantom proto.InternalMessageInfo

type SingleTuple struct {
	Fields               []*SingleValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SingleTuple) Reset()         { *m = SingleTuple{} }
func (m *SingleTuple) String() string { return proto.CompactTextString(m) }
func (*SingleTuple) ProtoMessage()    {}
func (*SingleTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{13}
}

func (m *SingleTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleTuple.Unmarshal(m, b)
}
func (m *SingleTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleTuple.Marshal(b, m, deterministic)
}
func (m *SingleTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleTuple.Merge(m, src)
}
func (m *SingleTuple) XXX_Size() int {
	return xxx_messageInfo_SingleTuple.Size(m)
}
func (m *SingleTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleTuple.DiscardUnknown(m)
}

var xxx_messageInfo_SingleTuple proto.InternalMessageInfo

func (m *SingleTuple) GetFields() []*SingleValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SingleObject struct {
	Fields               map[string]*SingleValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SingleObject) Reset()         { *m = SingleObject{} }
func (m *SingleObject) String() string { return proto.CompactTextString(m) }
func (*SingleObject) ProtoMessage()    {}
func (*SingleObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{14}
}

func (m *SingleObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleObject.Unmarshal(m, b)
}
func (m *SingleObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleObject.Marshal(b, m, deterministic)
}
func (m *SingleObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleObject.Merge(m, src)
}
func (m *SingleObject) XXX_Size() int {
	return xxx_messageInfo_SingleObject.Size(m)
}
func (m *SingleObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleObject.DiscardUnknown(m)
}

var xxx_messageInfo_SingleObject proto.InternalMessageInfo

func (m *SingleObject) GetFields() map[string]*SingleValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SingleValue struct {
	// Types that are valid to be assigned to Value:
	//	*SingleValue_Null
	//	*SingleValue_Phantom
	//	*SingleValue_Int
	//	*SingleValue_Float
	//	*SingleValue_Bool
	//	*SingleValue_String_
	//	*SingleValue_Time
	//	*SingleValue_Duration
	//	*SingleValue_Tuple
	//	*SingleValue_Object
	Value                isSingleValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SingleValue) Reset()         { *m = SingleValue{} }
func (m *SingleValue) String() string { return proto.CompactTextString(m) }
func (*SingleValue) ProtoMessage()    {}
func (*SingleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{15}
}

func (m *SingleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleValue.Unmarshal(m, b)
}
func (m *SingleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleValue.Marshal(b, m, deterministic)
}
func (m *SingleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleValue.Merge(m, src)
}
func (m *SingleValue) XXX_Size() int {
	return xxx_messageInfo_SingleValue.Size(m)
}
func (m *SingleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleValue.DiscardUnknown(m)
}

var xxx_messageInfo_SingleValue proto.InternalMessageInfo

type isSingleValue_Value interface {
	isSingleValue_Value()
}

type SingleValue_Null struct {
	Null *Null `protobuf:"bytes,1,opt,name=null,proto3,oneof"`
}

type SingleValue_Phantom struct {
	Phantom *Phantom `protobuf:"bytes,2,opt,name=phantom,proto3,oneof"`
}

type SingleValue_Int struct {
	Int int64 `protobuf:"varint,3,opt,name=int,proto3,oneof"`
}

type SingleValue_Float struct {
	Float float64 `protobuf:"fixed64,4,opt,name=float,proto3,oneof"`
}

type SingleValue_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

type SingleValue_String_ struct {
	String_ string `protobuf:"bytes,6,opt,name=string,proto3,oneof"`
}

type SingleValue_Time struct {
	Time *timestamp.Timestamp `protobuf:"bytes,7,opt,name=time,proto3,oneof"`
}

type SingleValue_Duration struct {
	Duration *duration.Duration `protobuf:"bytes,8,opt,name=duration,proto3,oneof"`
}

type SingleValue_Tuple struct {
	Tuple *SingleTuple `protobuf:"bytes,9,opt,name=tuple,proto3,oneof"`
}

type SingleValue_Object struct {
	Object *SingleObject `protobuf:"bytes,10,opt,name=object,proto3,oneof"`
}

func (*SingleValue_Null) isSingleValue_Value() {}

func (*SingleValue_Phantom) isSingleValue_Value() {}

func (*SingleValue_Int) isSingleValue_Value() {}

func (*SingleValue_Float) isSingleValue_Value() {}

func (*SingleValue_Bool) isSingleValue_Value() {}

func (*SingleValue_String_) isSingleValue_Value() {}

func (*SingleValue_Time) isSingleValue_Value() {}

func (*SingleValue_Duration) isSingleValue_Value() {}

func (*SingleValue_Tuple) isSingleValue_Value() {}

func (*SingleValue_Object) isSingleValue_Value() {}

func (m *SingleValue) GetValue() isSingleValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SingleValue) GetNull() *Null {
	if x, ok := m.GetValue().(*SingleValue_Null); ok {
		return x.Null
	}
	return nil
}

func (m *SingleValue) GetPhantom() *Phantom {
	if x, ok := m.GetValue().(*SingleValue_Phantom); ok {
		return x.Phantom
	}
	return nil
}

func (m *SingleValue) GetInt() int64 {
	if x, ok := m.GetValue().(*SingleValue_Int); ok {
		return x.Int
	}
	return 0
}

func (m *SingleValue) GetFloat() float64 {
	if x, ok := m.GetValue().(*SingleValue_Float); ok {
		return x.Float
	}
	return 0
}

func (m *SingleValue) GetBool() bool {
	if x, ok := m.GetValue().(*SingleValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *SingleValue) GetString_() string {
	if x, ok := m.GetValue().(*SingleValue_String_); ok {
		return x.String_
	}
	return ""
}

func (m *SingleValue) GetTime() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*SingleValue_Time); ok {
		return x.Time
	}
	return nil
}

func (m *SingleValue) GetDuration() *duration.Duration {
	if x, ok := m.GetValue().(*SingleValue_Duration); ok {
		return x.Duration
	}
	return nil
}

func (m *SingleValue) GetTuple() *SingleTuple {
	if x, ok := m.GetValue().(*SingleValue_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *SingleValue) GetObject() *SingleObject {
	if x, ok := m.GetValue().(*SingleValue_Object); ok {
		return x.Object
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SingleValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SingleValue_Null)(nil),
		(*SingleValue_Phantom)(nil),
		(*SingleValue_Int)(nil),
		(*SingleValue_Float)(nil),
		(*SingleValue_Bool)(nil),
		(*SingleValue_String_)(nil),
		(*SingleValue_Time)(nil),
		(*SingleValue_Duration)(nil),
		(*SingleValue_Tuple)(nil),
		(*SingleValue_Object)(nil),
	}
}

func init() {
	proto.RegisterType((*Nulls)(nil), "octosql.Nulls")
	proto.RegisterType((*Phantoms)(nil), "octosql.Phantoms")
	proto.RegisterType((*Ints)(nil), "octosql.Ints")
	proto.RegisterType((*Floats)(nil), "octosql.Floats")
	proto.RegisterType((*Bools)(nil), "octosql.Bools")
	proto.RegisterType((*Strings)(nil), "octosql.Strings")
	proto.RegisterType((*Times)(nil), "octosql.Times")
	proto.RegisterType((*Durations)(nil), "octosql.Durations")
	proto.RegisterType((*Tuple)(nil), "octosql.Tuple")
	proto.RegisterType((*Object)(nil), "octosql.Object")
	proto.RegisterMapType((map[string]*Value)(nil), "octosql.Object.FieldsEntry")
	proto.RegisterType((*Value)(nil), "octosql.Value")
	proto.RegisterType((*Null)(nil), "octosql.Null")
	proto.RegisterType((*Phantom)(nil), "octosql.Phantom")
	proto.RegisterType((*SingleTuple)(nil), "octosql.SingleTuple")
	proto.RegisterType((*SingleObject)(nil), "octosql.SingleObject")
	proto.RegisterMapType((map[string]*SingleValue)(nil), "octosql.SingleObject.FieldsEntry")
	proto.RegisterType((*SingleValue)(nil), "octosql.SingleValue")
}

func init() { proto.RegisterFile("values.proto", fileDescriptor_5d19e76c3b90e014) }

var fileDescriptor_5d19e76c3b90e014 = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x41, 0x4f, 0xdb, 0x3e,
	0x14, 0xc0, 0x1b, 0xd2, 0x24, 0xcd, 0x03, 0xfe, 0x7f, 0x66, 0x31, 0xe4, 0x15, 0xb1, 0x15, 0x83,
	0x18, 0x43, 0x2c, 0x45, 0xe5, 0xc0, 0xd8, 0x6e, 0x88, 0xa1, 0x72, 0x19, 0x93, 0x41, 0x3b, 0xec,
	0xd6, 0x94, 0xb4, 0x64, 0x4b, 0xe3, 0xae, 0x71, 0x26, 0xf1, 0x0d, 0x76, 0xdb, 0x7d, 0x1f, 0x62,
	0x9f, 0x71, 0xb2, 0x1d, 0xa7, 0x89, 0xe9, 0xd8, 0xcd, 0xf1, 0xfb, 0xbd, 0xa7, 0xf7, 0xfc, 0x7e,
	0x0a, 0xac, 0x7c, 0x1f, 0x24, 0x79, 0x94, 0x05, 0xd3, 0x19, 0xe3, 0x0c, 0x79, 0x6c, 0xc8, 0x59,
	0xf6, 0x2d, 0x69, 0xbf, 0x18, 0x33, 0x36, 0x4e, 0xa2, 0xae, 0xbc, 0x0e, 0xf3, 0x51, 0x97, 0xc7,
	0x93, 0x28, 0xe3, 0x83, 0xc9, 0x54, 0x91, 0xed, 0xe7, 0x26, 0x70, 0x9b, 0xcf, 0x06, 0x3c, 0x66,
	0xa9, 0x8a, 0x13, 0x0f, 0x9c, 0x0f, 0x79, 0x92, 0x64, 0x04, 0xa0, 0xf5, 0xf1, 0x6e, 0x90, 0x72,
	0x36, 0xc9, 0x48, 0x1b, 0x9a, 0x97, 0x29, 0xcf, 0x10, 0x82, 0x66, 0x9c, 0xf2, 0x0c, 0x5b, 0x1d,
	0x7b, 0xdf, 0xa6, 0xf2, 0x4c, 0x3a, 0xe0, 0x5e, 0x24, 0x6c, 0xc0, 0x33, 0xb4, 0x01, 0xee, 0x48,
	0x9e, 0x64, 0xdc, 0xa2, 0xc5, 0x17, 0xd9, 0x02, 0xe7, 0x8c, 0xb1, 0x24, 0x43, 0xeb, 0xe0, 0x84,
	0xe2, 0x20, 0xe3, 0x2d, 0xaa, 0x3e, 0xc8, 0x0e, 0x78, 0xd7, 0x7c, 0x16, 0xa7, 0xe3, 0x0c, 0x61,
	0xf0, 0x32, 0x75, 0x94, 0x88, 0x4f, 0xf5, 0x27, 0x39, 0x05, 0xe7, 0x46, 0x4c, 0x82, 0x8e, 0xc0,
	0x91, 0x23, 0x49, 0x60, 0xb9, 0xd7, 0x0e, 0xd4, 0x3c, 0x81, 0x9e, 0x27, 0xb8, 0xd1, 0x03, 0x53,
	0x05, 0x92, 0x73, 0xf0, 0xcf, 0x8b, 0x19, 0x33, 0x74, 0x02, 0xbe, 0x1e, 0x58, 0x97, 0x78, 0xf6,
	0xa0, 0x84, 0xc6, 0xe9, 0x9c, 0x25, 0x5d, 0x70, 0x6e, 0xf2, 0x69, 0x12, 0xa1, 0x3d, 0x70, 0x47,
	0x71, 0x94, 0xdc, 0xea, 0xf4, 0xff, 0x82, 0xe2, 0xed, 0x83, 0x4f, 0x62, 0x23, 0xb4, 0x88, 0x92,
	0x1f, 0x16, 0xb8, 0x57, 0xe1, 0x97, 0x68, 0xc8, 0xd1, 0xb1, 0x91, 0xb2, 0x59, 0xa6, 0x28, 0x20,
	0xb8, 0x90, 0xd1, 0xf7, 0x29, 0x9f, 0xdd, 0xeb, 0xfc, 0xf6, 0x25, 0x2c, 0x57, 0xae, 0xd1, 0x1a,
	0xd8, 0x5f, 0xa3, 0x7b, 0x6c, 0x75, 0xac, 0x7d, 0x9f, 0x8a, 0x23, 0xda, 0x05, 0x47, 0x3a, 0x80,
	0x97, 0x3a, 0xd6, 0x82, 0x3e, 0x54, 0xf0, 0xed, 0xd2, 0x1b, 0x8b, 0xfc, 0xb6, 0xc1, 0x91, 0x97,
	0x68, 0x17, 0x9a, 0x69, 0x9e, 0x24, 0xb2, 0x4c, 0x35, 0x45, 0xae, 0xbc, 0xdf, 0xa0, 0x32, 0x8a,
	0x5e, 0x83, 0x37, 0x55, 0xab, 0x2f, 0x6a, 0x3f, 0x29, 0x41, 0xad, 0x44, 0xbf, 0x41, 0x35, 0x83,
	0xb6, 0xc1, 0x8e, 0x53, 0x8e, 0x6d, 0x89, 0xae, 0x96, 0xa8, 0x30, 0xa6, 0xdf, 0xa0, 0x22, 0x86,
	0x5e, 0x82, 0x23, 0x65, 0xc0, 0x4d, 0x09, 0xfd, 0x5f, 0x42, 0x4a, 0x9d, 0x7e, 0x83, 0xaa, 0xb8,
	0x68, 0x50, 0x58, 0x81, 0x1d, 0xa3, 0x41, 0x29, 0x90, 0x68, 0x50, 0x44, 0xd1, 0x01, 0xb8, 0x4a,
	0x0c, 0xec, 0x4a, 0x6e, 0xad, 0xe4, 0x0a, 0x93, 0xfa, 0x0d, 0x5a, 0x10, 0xa2, 0xa2, 0xf0, 0x00,
	0x7b, 0x46, 0x45, 0xe9, 0x89, 0xa8, 0x28, 0xa2, 0xe8, 0x08, 0x5a, 0x7a, 0xd7, 0xb8, 0x25, 0x49,
	0x54, 0x92, 0xa5, 0x3d, 0xfd, 0x06, 0x2d, 0x29, 0xb4, 0x07, 0x0e, 0x17, 0x42, 0x60, 0xdf, 0x2c,
	0x2c, 0x6e, 0xc5, 0x44, 0x32, 0x8c, 0x5e, 0x81, 0xcb, 0xe4, 0x96, 0x31, 0x18, 0xb3, 0xab, 0xe5,
	0x8b, 0x56, 0x15, 0x70, 0xe6, 0x15, 0x1b, 0x25, 0x2e, 0x34, 0xc5, 0x46, 0x88, 0x0f, 0x5e, 0xf1,
	0xe0, 0xe4, 0x1d, 0x2c, 0x5f, 0xc7, 0xe9, 0x38, 0x89, 0x94, 0x85, 0x87, 0x86, 0x52, 0xeb, 0xf3,
	0x17, 0x90, 0x54, 0xdd, 0xc5, 0x5f, 0x16, 0xac, 0xa8, 0xfb, 0xc2, 0xc8, 0x53, 0x23, 0x7d, 0xdb,
	0x48, 0x7f, 0xc4, 0xcb, 0xab, 0x7f, 0x79, 0x79, 0x50, 0xf7, 0x72, 0x71, 0x67, 0x15, 0x3b, 0x7f,
	0xda, 0x7a, 0x34, 0xe5, 0xe8, 0x4e, 0xcd, 0xd1, 0xd5, 0x9a, 0xa3, 0xa5, 0xa2, 0x87, 0xa6, 0xa2,
	0x6b, 0xa6, 0xa2, 0x55, 0x43, 0xd1, 0xdc, 0x50, 0x5b, 0x2b, 0xb9, 0x51, 0x55, 0xd2, 0x9a, 0x1b,
	0xb8, 0x5e, 0x31, 0xb0, 0x55, 0x1a, 0x87, 0x6b, 0xc6, 0xf9, 0x15, 0xbf, 0x8e, 0x6a, 0x7e, 0x3d,
	0xf2, 0x3f, 0x2a, 0x5d, 0x3b, 0x79, 0xe0, 0xda, 0xdf, 0x7f, 0x41, 0x35, 0xe5, 0x0e, 0xeb, 0xca,
	0x99, 0x2f, 0x6b, 0x88, 0xd7, 0x35, 0xc4, 0x7b, 0xba, 0x70, 0xc7, 0x0b, 0xf4, 0x3b, 0xdb, 0xfa,
	0xbc, 0x39, 0x8e, 0xf9, 0x5d, 0x1e, 0x06, 0x43, 0x36, 0xe9, 0x0e, 0xf3, 0x30, 0xea, 0xf5, 0x7a,
	0xbd, 0x6e, 0x91, 0x1e, 0xba, 0xb2, 0xcb, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x54,
	0xbc, 0xa0, 0x83, 0x06, 0x00, 0x00,
}
