// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execution/process.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueElement struct {
	// Types that are valid to be assigned to Type:
	//	*QueueElement_Record
	//	*QueueElement_Watermark
	//	*QueueElement_EndOfStream
	//	*QueueElement_Error
	Type                 isQueueElement_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueueElement) Reset()         { *m = QueueElement{} }
func (m *QueueElement) String() string { return proto.CompactTextString(m) }
func (*QueueElement) ProtoMessage()    {}
func (*QueueElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9889a525e12bbaa, []int{0}
}

func (m *QueueElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueElement.Unmarshal(m, b)
}
func (m *QueueElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueElement.Marshal(b, m, deterministic)
}
func (m *QueueElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueElement.Merge(m, src)
}
func (m *QueueElement) XXX_Size() int {
	return xxx_messageInfo_QueueElement.Size(m)
}
func (m *QueueElement) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueElement.DiscardUnknown(m)
}

var xxx_messageInfo_QueueElement proto.InternalMessageInfo

type isQueueElement_Type interface {
	isQueueElement_Type()
}

type QueueElement_Record struct {
	Record *RecordData `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type QueueElement_Watermark struct {
	Watermark *timestamp.Timestamp `protobuf:"bytes,2,opt,name=watermark,proto3,oneof"`
}

type QueueElement_EndOfStream struct {
	EndOfStream bool `protobuf:"varint,3,opt,name=endOfStream,proto3,oneof"`
}

type QueueElement_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*QueueElement_Record) isQueueElement_Type() {}

func (*QueueElement_Watermark) isQueueElement_Type() {}

func (*QueueElement_EndOfStream) isQueueElement_Type() {}

func (*QueueElement_Error) isQueueElement_Type() {}

func (m *QueueElement) GetType() isQueueElement_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *QueueElement) GetRecord() *RecordData {
	if x, ok := m.GetType().(*QueueElement_Record); ok {
		return x.Record
	}
	return nil
}

func (m *QueueElement) GetWatermark() *timestamp.Timestamp {
	if x, ok := m.GetType().(*QueueElement_Watermark); ok {
		return x.Watermark
	}
	return nil
}

func (m *QueueElement) GetEndOfStream() bool {
	if x, ok := m.GetType().(*QueueElement_EndOfStream); ok {
		return x.EndOfStream
	}
	return false
}

func (m *QueueElement) GetError() string {
	if x, ok := m.GetType().(*QueueElement_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueueElement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueueElement_Record)(nil),
		(*QueueElement_Watermark)(nil),
		(*QueueElement_EndOfStream)(nil),
		(*QueueElement_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*QueueElement)(nil), "execution.QueueElement")
}

func init() { proto.RegisterFile("execution/process.proto", fileDescriptor_c9889a525e12bbaa) }

var fileDescriptor_c9889a525e12bbaa = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x41, 0x2b, 0x91, 0xad, 0x27, 0x12, 0x2b, 0xe1, 0x22, 0x69, 0x62, 0xe4, 0xb4, 0x9b,
	0xe0, 0xcd, 0x63, 0xa3, 0x09, 0x37, 0x23, 0x7a, 0xf2, 0xb6, 0x6c, 0xa7, 0x48, 0x64, 0x19, 0x1c,
	0x66, 0xa3, 0xfe, 0x3a, 0xff, 0x9a, 0x09, 0x58, 0xda, 0xe3, 0x9b, 0xf7, 0xcd, 0x7b, 0x4f, 0x5c,
	0xc1, 0x37, 0x18, 0xc7, 0x0d, 0x76, 0xaa, 0x27, 0x34, 0x30, 0x0c, 0xb2, 0x27, 0x64, 0x8c, 0xc2,
	0xd9, 0x48, 0x56, 0x07, 0x86, 0xc0, 0x20, 0x6d, 0x27, 0x24, 0xb9, 0xae, 0x11, 0xeb, 0x16, 0xd4,
	0xa8, 0x2a, 0xb7, 0x53, 0xdc, 0x58, 0x18, 0x58, 0xdb, 0x7e, 0x02, 0xd6, 0xbf, 0xbe, 0xb8, 0x78,
	0x76, 0xe0, 0xe0, 0xb1, 0x05, 0x0b, 0x1d, 0x47, 0x4a, 0x04, 0x53, 0x42, 0xec, 0xa7, 0x7e, 0xb6,
	0xcc, 0x2f, 0xe5, 0x1c, 0x2d, 0xcb, 0xd1, 0x78, 0xd0, 0xac, 0x0b, 0xaf, 0xfc, 0xc7, 0xa2, 0x7b,
	0x11, 0x7e, 0x69, 0x06, 0xb2, 0x9a, 0x3e, 0xe2, 0x93, 0xf1, 0x27, 0x91, 0x53, 0xad, 0xdc, 0xd7,
	0xca, 0xd7, 0x7d, 0x6d, 0xe1, 0x95, 0x07, 0x3c, 0x5a, 0x8b, 0x25, 0x74, 0xdb, 0xa7, 0xdd, 0x0b,
	0x13, 0x68, 0x1b, 0x9f, 0xa6, 0x7e, 0x76, 0x5e, 0x78, 0xe5, 0xf1, 0x31, 0x5a, 0x89, 0x33, 0x20,
	0x42, 0x8a, 0x17, 0xa9, 0x9f, 0x85, 0x85, 0x57, 0x4e, 0x72, 0x13, 0x88, 0x05, 0xff, 0xf4, 0xb0,
	0xb9, 0x7d, 0xbb, 0xa9, 0x1b, 0x7e, 0x77, 0x95, 0x34, 0x68, 0x95, 0x71, 0x15, 0xe4, 0x79, 0x9e,
	0x2b, 0x34, 0x8c, 0xc3, 0x67, 0xab, 0xe6, 0xf5, 0x55, 0x30, 0xae, 0xb9, 0xfb, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xad, 0xc6, 0x32, 0x0b, 0x50, 0x01, 0x00, 0x00,
}
