// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Metadata struct {
	Id                   *ID      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Undo                 bool     `protobuf:"varint,2,opt,name=undo,proto3" json:"undo,omitempty"`
	EventTimeField       string   `protobuf:"bytes,3,opt,name=eventTimeField,proto3" json:"eventTimeField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetId() *ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Metadata) GetUndo() bool {
	if m != nil {
		return m.Undo
	}
	return false
}

func (m *Metadata) GetEventTimeField() string {
	if m != nil {
		return m.EventTimeField
	}
	return ""
}

type Record struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FieldNames           []string  `protobuf:"bytes,2,rep,name=fieldNames,proto3" json:"fieldNames,omitempty"`
	Data                 []int64   `protobuf:"varint,3,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{2}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Record) GetFieldNames() []string {
	if m != nil {
		return m.FieldNames
	}
	return nil
}

func (m *Record) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "execution.ID")
	proto.RegisterType((*Metadata)(nil), "execution.Metadata")
	proto.RegisterType((*Record)(nil), "execution.Record")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xad, 0x48, 0x4d, 0x2e, 0x2d,
	0xc9, 0xcc, 0xcf, 0x53, 0x12, 0xe1, 0x62, 0xf2, 0x74, 0x11, 0xe2, 0x03, 0x91, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e, 0x2e, 0x4a, 0xa9, 0x5c, 0x1c, 0xbe, 0xa9, 0x25, 0x89, 0x29,
	0x89, 0x25, 0x89, 0x42, 0xb2, 0x5c, 0x4c, 0x99, 0x29, 0x60, 0x39, 0x6e, 0x23, 0x5e, 0x3d, 0xb8,
	0x4e, 0x3d, 0x4f, 0x97, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xd2, 0xbc, 0x94, 0x7c,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x30, 0x5b, 0x48, 0x8d, 0x8b, 0x2f, 0xb5, 0x2c, 0x35,
	0xaf, 0x24, 0x24, 0x33, 0x37, 0xd5, 0x2d, 0x33, 0x35, 0x27, 0x45, 0x82, 0x19, 0x6c, 0x34, 0x9a,
	0xa8, 0x52, 0x2e, 0x17, 0x5b, 0x10, 0xd8, 0x5d, 0x42, 0xfa, 0x5c, 0x1c, 0xb9, 0x50, 0x0b, 0xa1,
	0x56, 0x09, 0x23, 0x59, 0x05, 0x73, 0x4b, 0x10, 0x5c, 0x91, 0x90, 0x1c, 0x17, 0x57, 0x1a, 0xc8,
	0x0c, 0xbf, 0xc4, 0xdc, 0xd4, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x90,
	0xb3, 0xc0, 0x86, 0x31, 0x2b, 0x30, 0x6b, 0x30, 0x07, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xdf, 0x1b,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xdb, 0x3a, 0x70, 0x0d, 0x01, 0x00, 0x00,
}
