// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execution/shuffle.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShuffleID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShuffleID) Reset()         { *m = ShuffleID{} }
func (m *ShuffleID) String() string { return proto.CompactTextString(m) }
func (*ShuffleID) ProtoMessage()    {}
func (*ShuffleID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0af0a146a0c7d88d, []int{0}
}

func (m *ShuffleID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShuffleID.Unmarshal(m, b)
}
func (m *ShuffleID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShuffleID.Marshal(b, m, deterministic)
}
func (m *ShuffleID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShuffleID.Merge(m, src)
}
func (m *ShuffleID) XXX_Size() int {
	return xxx_messageInfo_ShuffleID.Size(m)
}
func (m *ShuffleID) XXX_DiscardUnknown() {
	xxx_messageInfo_ShuffleID.DiscardUnknown(m)
}

var xxx_messageInfo_ShuffleID proto.InternalMessageInfo

func (m *ShuffleID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ShuffleID)(nil), "execution.ShuffleID")
}

func init() { proto.RegisterFile("execution/shuffle.proto", fileDescriptor_0af0a146a0c7d88d) }

var fileDescriptor_0af0a146a0c7d88d = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xad, 0x48, 0x4d,
	0x2e, 0x2d, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0xce, 0x28, 0x4d, 0x4b, 0xcb, 0x49, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x4b, 0x28, 0x49, 0x73, 0x71, 0x06, 0x43, 0xe4, 0x3c, 0x5d,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53,
	0x9c, 0xd4, 0xa3, 0x54, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93,
	0x4b, 0x93, 0x52, 0x8d, 0x8c, 0x8c, 0x8c, 0xf4, 0xf3, 0x93, 0x4b, 0xf2, 0x8b, 0x0b, 0x73, 0xf4,
	0xe1, 0xa6, 0x24, 0xb1, 0x81, 0xcd, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x16, 0xc9,
	0xcc, 0x72, 0x00, 0x00, 0x00,
}
