// Code generated by 'yaegi extract github.com/cube2222/octosql/execution/files'. DO NOT EDIT.

package codegen

import (
	"github.com/cube2222/octosql/execution/files"
	"reflect"
)

func init() {
	Symbols["github.com/cube2222/octosql/execution/files/files"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"OpenLocalFile": reflect.ValueOf(files.OpenLocalFile),
		"Tail":          reflect.ValueOf(files.Tail),
		"WithPreview":   reflect.ValueOf(files.WithPreview),
		"WithTail":      reflect.ValueOf(files.WithTail),

		// type definitions
		"OpenFileOption": reflect.ValueOf((*files.OpenFileOption)(nil)),
	}
}
