// Code generated by 'yaegi extract github.com/cube2222/octosql/codegen/lib'. DO NOT EDIT.

package codegen

import (
	"github.com/cube2222/octosql/codegen/lib"
	"reflect"
)

func init() {
	Symbols["github.com/cube2222/octosql/codegen/lib/lib"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NoUnusedMark": reflect.ValueOf(lib.NoUnusedMark),

		// type definitions
		"AggregateAvgFloat": reflect.ValueOf((*lib.AggregateAvgFloat)(nil)),
		"AggregateCount":    reflect.ValueOf((*lib.AggregateCount)(nil)),
		"AggregateSumInt":   reflect.ValueOf((*lib.AggregateSumInt)(nil)),
	}
}
