// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datasources/kafka/kafka.proto

package kafka

import (
	fmt "fmt"
	execution "github.com/cube2222/octosql/execution"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueElement struct {
	// Types that are valid to be assigned to Type:
	//	*QueueElement_Record
	//	*QueueElement_Error
	Type                 isQueueElement_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueueElement) Reset()         { *m = QueueElement{} }
func (m *QueueElement) String() string { return proto.CompactTextString(m) }
func (*QueueElement) ProtoMessage()    {}
func (*QueueElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_118b046d139daa5a, []int{0}
}

func (m *QueueElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueElement.Unmarshal(m, b)
}
func (m *QueueElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueElement.Marshal(b, m, deterministic)
}
func (m *QueueElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueElement.Merge(m, src)
}
func (m *QueueElement) XXX_Size() int {
	return xxx_messageInfo_QueueElement.Size(m)
}
func (m *QueueElement) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueElement.DiscardUnknown(m)
}

var xxx_messageInfo_QueueElement proto.InternalMessageInfo

type isQueueElement_Type interface {
	isQueueElement_Type()
}

type QueueElement_Record struct {
	Record *execution.Record `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type QueueElement_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QueueElement_Record) isQueueElement_Type() {}

func (*QueueElement_Error) isQueueElement_Type() {}

func (m *QueueElement) GetType() isQueueElement_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *QueueElement) GetRecord() *execution.Record {
	if x, ok := m.GetType().(*QueueElement_Record); ok {
		return x.Record
	}
	return nil
}

func (m *QueueElement) GetError() string {
	if x, ok := m.GetType().(*QueueElement_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueueElement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueueElement_Record)(nil),
		(*QueueElement_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*QueueElement)(nil), "kafka.QueueElement")
}

func init() { proto.RegisterFile("datasources/kafka/kafka.proto", fileDescriptor_118b046d139daa5a) }

var fileDescriptor_118b046d139daa5a = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x49, 0x2c, 0x49,
	0x2c, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0xd6, 0xcf, 0x4e, 0x4c, 0xcb, 0x4e, 0x84, 0x90, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x94, 0x58, 0x6a, 0x45, 0x6a, 0x72, 0x69,
	0x49, 0x66, 0x7e, 0x9e, 0x7e, 0x51, 0x6a, 0x72, 0x7e, 0x51, 0x0a, 0x44, 0x5a, 0x29, 0x9a, 0x8b,
	0x27, 0xb0, 0x34, 0xb5, 0x34, 0xd5, 0x35, 0x27, 0x35, 0x37, 0x35, 0xaf, 0x44, 0x48, 0x9b, 0x8b,
	0x0d, 0x22, 0x2f, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa8, 0x07, 0xd7, 0xa8, 0x17, 0x04,
	0x96, 0xf0, 0x60, 0x08, 0x82, 0x2a, 0x11, 0x12, 0xe3, 0x62, 0x4d, 0x2d, 0x2a, 0xca, 0x2f, 0x92,
	0x60, 0x52, 0x60, 0xd4, 0xe0, 0xf4, 0x60, 0x08, 0x82, 0x70, 0x9d, 0xd8, 0xb8, 0x58, 0x4a, 0x2a,
	0x0b, 0x52, 0x9d, 0xf4, 0xa3, 0x74, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73,
	0xf5, 0x93, 0x4b, 0x93, 0x52, 0x8d, 0x8c, 0x8c, 0x8c, 0xf4, 0xf3, 0x93, 0x4b, 0xf2, 0x8b, 0x0b,
	0x73, 0xf4, 0x31, 0x1c, 0x9e, 0xc4, 0x06, 0x76, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xaa, 0x6b, 0x2e, 0xd4, 0x00, 0x00, 0x00,
}
