// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package model

import (
	"bytes"
	"context"
	"reflect"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

// Attributes:
//  - FooString
//  - FooInt16
//  - FooInt32
//  - FooInt64
//  - FooDouble
//  - FooByte
//  - FooBool
type Foo struct {
  FooString string `thrift:"fooString,1" db:"fooString" json:"fooString"`
  FooInt16 int16 `thrift:"fooInt16,2" db:"fooInt16" json:"fooInt16"`
  FooInt32 int32 `thrift:"fooInt32,3" db:"fooInt32" json:"fooInt32"`
  FooInt64 int64 `thrift:"fooInt64,4" db:"fooInt64" json:"fooInt64"`
  FooDouble float64 `thrift:"fooDouble,5" db:"fooDouble" json:"fooDouble"`
  FooByte int8 `thrift:"fooByte,6" db:"fooByte" json:"fooByte"`
  FooBool bool `thrift:"fooBool,7" db:"fooBool" json:"fooBool"`
}

func NewFoo() *Foo {
  return &Foo{}
}


func (p *Foo) GetFooString() string {
  return p.FooString
}

func (p *Foo) GetFooInt16() int16 {
  return p.FooInt16
}

func (p *Foo) GetFooInt32() int32 {
  return p.FooInt32
}

func (p *Foo) GetFooInt64() int64 {
  return p.FooInt64
}

func (p *Foo) GetFooDouble() float64 {
  return p.FooDouble
}

func (p *Foo) GetFooByte() int8 {
  return p.FooByte
}

func (p *Foo) GetFooBool() bool {
  return p.FooBool
}
func (p *Foo) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I16 {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField3(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField4(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.DOUBLE {
        if err := p.ReadField5(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 6:
      if fieldTypeId == thrift.BYTE {
        if err := p.ReadField6(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 7:
      if fieldTypeId == thrift.BOOL {
        if err := p.ReadField7(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *Foo)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.FooString = v
}
  return nil
}

func (p *Foo)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI16(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.FooInt16 = v
}
  return nil
}

func (p *Foo)  ReadField3(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.FooInt32 = v
}
  return nil
}

func (p *Foo)  ReadField4(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.FooInt64 = v
}
  return nil
}

func (p *Foo)  ReadField5(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadDouble(); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  p.FooDouble = v
}
  return nil
}

func (p *Foo)  ReadField6(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadByte(); err != nil {
  return thrift.PrependError("error reading field 6: ", err)
} else {
  temp := int8(v)
  p.FooByte = temp
}
  return nil
}

func (p *Foo)  ReadField7(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBool(); err != nil {
  return thrift.PrependError("error reading field 7: ", err)
} else {
  p.FooBool = v
}
  return nil
}

func (p *Foo) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("Foo"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
    if err := p.writeField4(oprot); err != nil { return err }
    if err := p.writeField5(oprot); err != nil { return err }
    if err := p.writeField6(oprot); err != nil { return err }
    if err := p.writeField7(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Foo) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooString", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:fooString: ", p), err) }
  if err := oprot.WriteString(string(p.FooString)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooString (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:fooString: ", p), err) }
  return err
}

func (p *Foo) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooInt16", thrift.I16, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:fooInt16: ", p), err) }
  if err := oprot.WriteI16(int16(p.FooInt16)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooInt16 (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:fooInt16: ", p), err) }
  return err
}

func (p *Foo) writeField3(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooInt32", thrift.I32, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:fooInt32: ", p), err) }
  if err := oprot.WriteI32(int32(p.FooInt32)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooInt32 (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:fooInt32: ", p), err) }
  return err
}

func (p *Foo) writeField4(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooInt64", thrift.I64, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:fooInt64: ", p), err) }
  if err := oprot.WriteI64(int64(p.FooInt64)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooInt64 (4) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:fooInt64: ", p), err) }
  return err
}

func (p *Foo) writeField5(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooDouble", thrift.DOUBLE, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:fooDouble: ", p), err) }
  if err := oprot.WriteDouble(float64(p.FooDouble)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooDouble (5) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:fooDouble: ", p), err) }
  return err
}

func (p *Foo) writeField6(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooByte", thrift.BYTE, 6); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:fooByte: ", p), err) }
  if err := oprot.WriteByte(int8(p.FooByte)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooByte (6) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 6:fooByte: ", p), err) }
  return err
}

func (p *Foo) writeField7(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("fooBool", thrift.BOOL, 7); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:fooBool: ", p), err) }
  if err := oprot.WriteBool(bool(p.FooBool)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.fooBool (7) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 7:fooBool: ", p), err) }
  return err
}

func (p *Foo) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Foo(%+v)", *p)
}

// Attributes:
//  - BarString
type Bar struct {
  BarString string `thrift:"barString,1" db:"barString" json:"barString"`
}

func NewBar() *Bar {
  return &Bar{}
}


func (p *Bar) GetBarString() string {
  return p.BarString
}
func (p *Bar) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *Bar)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.BarString = v
}
  return nil
}

func (p *Bar) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("Bar"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Bar) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("barString", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:barString: ", p), err) }
  if err := oprot.WriteString(string(p.BarString)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.barString (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:barString: ", p), err) }
  return err
}

func (p *Bar) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Bar(%+v)", *p)
}

// Attributes:
//  - A
//  - Bar
//  - Foo
//  - Lst
type Record struct {
  A string `thrift:"a,1" db:"a" json:"a"`
  // unused field # 2
  Bar *Bar `thrift:"bar,3" db:"bar" json:"bar,omitempty"`
  Foo *Foo `thrift:"foo,4,required" db:"foo" json:"foo"`
  Lst []string `thrift:"lst,5" db:"lst" json:"lst"`
}

func NewRecord() *Record {
  return &Record{}
}


func (p *Record) GetA() string {
  return p.A
}
var Record_Bar_DEFAULT *Bar
func (p *Record) GetBar() *Bar {
  if !p.IsSetBar() {
    return Record_Bar_DEFAULT
  }
return p.Bar
}
var Record_Foo_DEFAULT *Foo
func (p *Record) GetFoo() *Foo {
  if !p.IsSetFoo() {
    return Record_Foo_DEFAULT
  }
return p.Foo
}

func (p *Record) GetLst() []string {
  return p.Lst
}
func (p *Record) IsSetBar() bool {
  return p.Bar != nil
}

func (p *Record) IsSetFoo() bool {
  return p.Foo != nil
}

func (p *Record) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetFoo bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField3(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField4(iprot); err != nil {
          return err
        }
        issetFoo = true
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 5:
      if fieldTypeId == thrift.LIST {
        if err := p.ReadField5(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetFoo{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Foo is not set"));
  }
  return nil
}

func (p *Record)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.A = v
}
  return nil
}

func (p *Record)  ReadField3(iprot thrift.TProtocol) error {
  p.Bar = &Bar{}
  if err := p.Bar.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Bar), err)
  }
  return nil
}

func (p *Record)  ReadField4(iprot thrift.TProtocol) error {
  p.Foo = &Foo{}
  if err := p.Foo.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Foo), err)
  }
  return nil
}

func (p *Record)  ReadField5(iprot thrift.TProtocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make([]string, 0, size)
  p.Lst =  tSlice
  for i := 0; i < size; i ++ {
var _elem0 string
    if v, err := iprot.ReadString(); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _elem0 = v
}
    p.Lst = append(p.Lst, _elem0)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *Record) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("Record"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
    if err := p.writeField4(oprot); err != nil { return err }
    if err := p.writeField5(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *Record) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("a", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:a: ", p), err) }
  if err := oprot.WriteString(string(p.A)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.a (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:a: ", p), err) }
  return err
}

func (p *Record) writeField3(oprot thrift.TProtocol) (err error) {
  if p.IsSetBar() {
    if err := oprot.WriteFieldBegin("bar", thrift.STRUCT, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:bar: ", p), err) }
    if err := p.Bar.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Bar), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:bar: ", p), err) }
  }
  return err
}

func (p *Record) writeField4(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("foo", thrift.STRUCT, 4); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:foo: ", p), err) }
  if err := p.Foo.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Foo), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 4:foo: ", p), err) }
  return err
}

func (p *Record) writeField5(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("lst", thrift.LIST, 5); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:lst: ", p), err) }
  if err := oprot.WriteListBegin(thrift.STRING, len(p.Lst)); err != nil {
    return thrift.PrependError("error writing list begin: ", err)
  }
  for _, v := range p.Lst {
    if err := oprot.WriteString(string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteListEnd(); err != nil {
    return thrift.PrependError("error writing list end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 5:lst: ", p), err) }
  return err
}

func (p *Record) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("Record(%+v)", *p)
}

type ImageService interface {
  Ping(ctx context.Context) (err error)
  OpenRecords(ctx context.Context) (r int32, err error)
  // Parameters:
  //  - StreamID
  GetRecord(ctx context.Context, streamID int32) (r *Record, err error)
  Close(ctx context.Context) (err error)
}

type ImageServiceClient struct {
  c thrift.TClient
}

func NewImageServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ImageServiceClient {
  return &ImageServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewImageServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ImageServiceClient {
  return &ImageServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewImageServiceClient(c thrift.TClient) *ImageServiceClient {
  return &ImageServiceClient{
    c: c,
  }
}

func (p *ImageServiceClient) Client_() thrift.TClient {
  return p.c
}
func (p *ImageServiceClient) Ping(ctx context.Context) (err error) {
  var _args1 ImageServicePingArgs
  var _result2 ImageServicePingResult
  if err = p.Client_().Call(ctx, "ping", &_args1, &_result2); err != nil {
    return
  }
  return nil
}

func (p *ImageServiceClient) OpenRecords(ctx context.Context) (r int32, err error) {
  var _args3 ImageServiceOpenRecordsArgs
  var _result4 ImageServiceOpenRecordsResult
  if err = p.Client_().Call(ctx, "openRecords", &_args3, &_result4); err != nil {
    return
  }
  return _result4.GetSuccess(), nil
}

// Parameters:
//  - StreamID
func (p *ImageServiceClient) GetRecord(ctx context.Context, streamID int32) (r *Record, err error) {
  var _args5 ImageServiceGetRecordArgs
  _args5.StreamID = streamID
  var _result6 ImageServiceGetRecordResult
  if err = p.Client_().Call(ctx, "getRecord", &_args5, &_result6); err != nil {
    return
  }
  return _result6.GetSuccess(), nil
}

func (p *ImageServiceClient) Close(ctx context.Context) (err error) {
  var _args7 ImageServiceCloseArgs
  var _result8 ImageServiceCloseResult
  if err = p.Client_().Call(ctx, "close", &_args7, &_result8); err != nil {
    return
  }
  return nil
}

type ImageServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler ImageService
}

func (p *ImageServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *ImageServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *ImageServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewImageServiceProcessor(handler ImageService) *ImageServiceProcessor {

  self9 := &ImageServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self9.processorMap["ping"] = &imageServiceProcessorPing{handler:handler}
  self9.processorMap["openRecords"] = &imageServiceProcessorOpenRecords{handler:handler}
  self9.processorMap["getRecord"] = &imageServiceProcessorGetRecord{handler:handler}
  self9.processorMap["close"] = &imageServiceProcessorClose{handler:handler}
return self9
}

func (p *ImageServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x10 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x10.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush(ctx)
  return false, x10

}

type imageServiceProcessorPing struct {
  handler ImageService
}

func (p *imageServiceProcessorPing) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := ImageServicePingArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("ping", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := ImageServicePingResult{}
  var err2 error
  if err2 = p.handler.Ping(ctx); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ping: " + err2.Error())
    oprot.WriteMessageBegin("ping", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  }
  if err2 = oprot.WriteMessageBegin("ping", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}

type imageServiceProcessorOpenRecords struct {
  handler ImageService
}

func (p *imageServiceProcessorOpenRecords) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := ImageServiceOpenRecordsArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("openRecords", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := ImageServiceOpenRecordsResult{}
var retval int32
  var err2 error
  if retval, err2 = p.handler.OpenRecords(ctx); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing openRecords: " + err2.Error())
    oprot.WriteMessageBegin("openRecords", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  } else {
    result.Success = &retval
}
  if err2 = oprot.WriteMessageBegin("openRecords", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}

type imageServiceProcessorGetRecord struct {
  handler ImageService
}

func (p *imageServiceProcessorGetRecord) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := ImageServiceGetRecordArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("getRecord", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := ImageServiceGetRecordResult{}
var retval *Record
  var err2 error
  if retval, err2 = p.handler.GetRecord(ctx, args.StreamID); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getRecord: " + err2.Error())
    oprot.WriteMessageBegin("getRecord", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  } else {
    result.Success = retval
}
  if err2 = oprot.WriteMessageBegin("getRecord", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}

type imageServiceProcessorClose struct {
  handler ImageService
}

func (p *imageServiceProcessorClose) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := ImageServiceCloseArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("close", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := ImageServiceCloseResult{}
  var err2 error
  if err2 = p.handler.Close(ctx); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing close: " + err2.Error())
    oprot.WriteMessageBegin("close", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  }
  if err2 = oprot.WriteMessageBegin("close", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

type ImageServicePingArgs struct {
}

func NewImageServicePingArgs() *ImageServicePingArgs {
  return &ImageServicePingArgs{}
}

func (p *ImageServicePingArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServicePingArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("ping_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServicePingArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServicePingArgs(%+v)", *p)
}

type ImageServicePingResult struct {
}

func NewImageServicePingResult() *ImageServicePingResult {
  return &ImageServicePingResult{}
}

func (p *ImageServicePingResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServicePingResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("ping_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServicePingResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServicePingResult(%+v)", *p)
}

type ImageServiceOpenRecordsArgs struct {
}

func NewImageServiceOpenRecordsArgs() *ImageServiceOpenRecordsArgs {
  return &ImageServiceOpenRecordsArgs{}
}

func (p *ImageServiceOpenRecordsArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceOpenRecordsArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("openRecords_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceOpenRecordsArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceOpenRecordsArgs(%+v)", *p)
}

// Attributes:
//  - Success
type ImageServiceOpenRecordsResult struct {
  Success *int32 `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewImageServiceOpenRecordsResult() *ImageServiceOpenRecordsResult {
  return &ImageServiceOpenRecordsResult{}
}

var ImageServiceOpenRecordsResult_Success_DEFAULT int32
func (p *ImageServiceOpenRecordsResult) GetSuccess() int32 {
  if !p.IsSetSuccess() {
    return ImageServiceOpenRecordsResult_Success_DEFAULT
  }
return *p.Success
}
func (p *ImageServiceOpenRecordsResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *ImageServiceOpenRecordsResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceOpenRecordsResult)  ReadField0(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 0: ", err)
} else {
  p.Success = &v
}
  return nil
}

func (p *ImageServiceOpenRecordsResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("openRecords_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceOpenRecordsResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.I32, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteI32(int32(*p.Success)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *ImageServiceOpenRecordsResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceOpenRecordsResult(%+v)", *p)
}

// Attributes:
//  - StreamID
type ImageServiceGetRecordArgs struct {
  StreamID int32 `thrift:"streamID,1" db:"streamID" json:"streamID"`
}

func NewImageServiceGetRecordArgs() *ImageServiceGetRecordArgs {
  return &ImageServiceGetRecordArgs{}
}


func (p *ImageServiceGetRecordArgs) GetStreamID() int32 {
  return p.StreamID
}
func (p *ImageServiceGetRecordArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceGetRecordArgs)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.StreamID = v
}
  return nil
}

func (p *ImageServiceGetRecordArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("getRecord_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceGetRecordArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("streamID", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:streamID: ", p), err) }
  if err := oprot.WriteI32(int32(p.StreamID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.streamID (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:streamID: ", p), err) }
  return err
}

func (p *ImageServiceGetRecordArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceGetRecordArgs(%+v)", *p)
}

// Attributes:
//  - Success
type ImageServiceGetRecordResult struct {
  Success *Record `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewImageServiceGetRecordResult() *ImageServiceGetRecordResult {
  return &ImageServiceGetRecordResult{}
}

var ImageServiceGetRecordResult_Success_DEFAULT *Record
func (p *ImageServiceGetRecordResult) GetSuccess() *Record {
  if !p.IsSetSuccess() {
    return ImageServiceGetRecordResult_Success_DEFAULT
  }
return p.Success
}
func (p *ImageServiceGetRecordResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *ImageServiceGetRecordResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceGetRecordResult)  ReadField0(iprot thrift.TProtocol) error {
  p.Success = &Record{}
  if err := p.Success.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *ImageServiceGetRecordResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("getRecord_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceGetRecordResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *ImageServiceGetRecordResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceGetRecordResult(%+v)", *p)
}

type ImageServiceCloseArgs struct {
}

func NewImageServiceCloseArgs() *ImageServiceCloseArgs {
  return &ImageServiceCloseArgs{}
}

func (p *ImageServiceCloseArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceCloseArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("close_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceCloseArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceCloseArgs(%+v)", *p)
}

type ImageServiceCloseResult struct {
}

func NewImageServiceCloseResult() *ImageServiceCloseResult {
  return &ImageServiceCloseResult{}
}

func (p *ImageServiceCloseResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ImageServiceCloseResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("close_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ImageServiceCloseResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ImageServiceCloseResult(%+v)", *p)
}


